name: Lint

on:
  push:

jobs:

  get-go-version:
    name: "Get Go Version 🐹"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout code 🛒"
        uses: actions/checkout@v3

      - name: "Get Go version from 'go.mod' 📎"
        id: get-go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

  lint:
    name: "Lint Go code 🐹"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout code 🛒"
      uses: actions/checkout@v2
      
    - name: "Setup Go 🐹"
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: "Install dependencies ⤵️"
      run: go mod download

    - name: "Run Go lint 👓"
      run: |
        go install golang.org/x/lint/golint
        golint ./...

    - name: "Check for Go vet 💉"
      run: go vet ./...
